---
# vars file for rhel8base
mount_options:
- mount: /var/tmp
  options: nosuid,noexec,nodev
- mount: /home
  options: nosuid,noexec,nodev
- mount: /var
  options: nosuid,nodev
- mount: /var/log/audit
  options: nodev,noexec
- mount: /var/log
  options: nodev,noexec

files_permissions:
- path: /etc/shadow
  owner: root
  group: root
  mode: "0000"
- path: /etc/gshadow
  owner: root
  group: root
  mode: "0000"
- path: /etc/passwd
  owner: root
  group: root
  mode: "0644"
- path: /etc/group
  owner: root
  group: root
  mode: "0644"
#- path: /etc/cron.allow
#  owner: root
#  group: root
#  mode: 0644
- path: /etc/grub2.cfg
  owner: root
  group: root
  mode: "0600"

disable_kernel_module:
- bluetooth
- cramfs
- dccp
- freevxfs
- hfs
- hfsplus
- jffs2
- squashfs
- udf
- usb-storage

disable_services:
- debug-shell

enable_services:
- auditd
- chronyd
- crond
- firewalld
- postfix

sysctl:
  net.ipv6.conf.all.disable_ipv6: 1
  kernel.randomize_va_space: 2
  kernel.kptr_restrict: 1
  kernel.kexec_load_disabled: 1
  kernel.dmesg_restrict: 1

