---
- import_tasks: tmp-mount.yml

- include_tasks: mount-options.yml
  loop: "{{ mount_options }}"
  loop_control:
    loop_var: mount
    label: "{{ mount.mount }}"

- include_tasks: disable_kernel_module.yml
  loop: "{{ disable_kernel_module }}"
  loop_control:
    loop_var: module

- name: set proper file permissions
  file:
    path: "{{ item.path }}" # required. Path to the file being managed.
    group: "{{ item.group }}" # not required. Name of the group that should own the file/directory, as would be fed to I(chown).
    state: file
    mode: "{{ item.mode}}"
    owner: "{{ item.owner }}" # not required. Name of the user that should own the file/directory, as would be fed to I(chown).
  loop: "{{ files_permissions }}"

- name: find ssh private keys
  find:
    paths: /etc/ssh
    patterns: "*_key"
  register: ssh_private_keys

- name: set private key permissions
  file:
    path: "{{ item.path }}"
    owner: "root"
    group: "ssh_keys"
    mode: "0640"
  loop: "{{ ssh_private_keys.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: find ssh public keys
  find:
    paths: /etc/ssh
    patterns: "*.pub"
  register: ssh_public_keys

- name: set public key permissions
  file:
    path: "{{ item.path }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop: "{{ ssh_public_keys.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: create /etc/cron.allow
  copy:
    content: root
    mode: 0644
    owner: root
    group: root
    dest: /etc/cron.allow

- name: remove /etc/cron.deny
  file:
    path: /etc/cron.deny
    state: absent